valortotal = float(input('Digite o valor total da conta: '))
quantpessoas = int(input('Divisão será para quantas pessoas? '))
divisao = (valortotal / quantpessoas)
print(f'O valor total é de R${valortotal} e dividido para {quantpessoas} pessoas, ficará R${divisao:.2f} para cada.')
saldo = float(input('Digite seu saldo: '))
resultado = (saldo >= divisao) and (divisao <= 100)
print('------------------------------')
print(f'Você tem saldo suficiente e a divisão é de até R$100? {resultado}')
print('------------------------------')